networks:
  desafio:
    name: desafio
    driver: bridge
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.45.6
    container_name: prometheus
    labels:
      - group=observability
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./observability/prometheus/alert-rules.yaml:/etc/prometheus/alert-rulers.rules
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    develop:
      watch:
        - action: sync+restart
          path: ./observability/prometheus/prometheus.yml
          target: /etc/prometheus/prometheus.yml:ro
        - action: sync+restart
          path: ./observability/prometheus/alert-rules.yaml
          target: /etc/prometheus/alert-rulers.rules
    ports:
      - 9090:9090
    networks:
      - desafio

  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    labels:
      - group=observability
    ports:
      - "3005:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      - desafio

  promtail:
    image: grafana/promtail:2.7.5
    container_name: promtail
    labels:
      - group=observability
    volumes:
      - ./observability/promtail/config.yaml:/etc/promtail/config.yml
      - ./observability/promtail/position/:/position/
      - /var/log/:/logs/syslogs/
      - ./catalog-api/logs/:/logs/producer/
    ports:
      - 9080:9080
    depends_on:
      - loki
    networks:
      - desafio

  loki:
    image: grafana/loki:2.7.5
    container_name: loki
    labels:
      - group=observability
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    ports:
      - 3100:3100
    networks:
      - desafio

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    labels:
      - group=observability
    volumes:
      - ./observability/prometheus/alert-manager.yaml:/prometheus/alertmanager.yml
    command:
      - "--config.file=/prometheus/alertmanager.yml"
    depends_on:
      - prometheus
    develop:
      watch:
        - action: sync+restart
          path: ./observability/prometheus/alert-manager.yaml
          target: /prometheus/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - desafio

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    labels:
      - group=observability
    user: root
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - desafio

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    labels:
      - group=observability
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - desafio
