version: "3.8"

networks:
  desafio:
    driver: bridge
    external: true

services:
  producer:
    image: deirofelippe/producer-anotaai-challenge:latest
    build:
      context: ./catalog-api
      dockerfile: Dockerfile.prod
    container_name: producer
    labels:
      - group=main
    # command: "sleep inf"
    env_file:
      - ./catalog-api/.env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - "./catalog-api:/home/node/app"
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - desafio
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  consumer:
    image: deirofelippe/consumer-anotaai-challenge:latest
    build:
      context: ./catalog-emit-consumer
      dockerfile: Dockerfile.prod
    container_name: consumer
    labels:
      - group=main
    # command: "sleep inf"
    env_file:
      - ./catalog-emit-consumer/.env
    ports:
      - 3001:3000
      - 9239:9229
    volumes:
      - "./catalog-emit-consumer:/home/node/app"
    networks:
      - desafio
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  rabbitmq:
    image: rabbitmq:3.9.29-management
    container_name: rabbitmq
    labels:
      - group=main
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      # - ./.rabbitmq_data/:/var/lib/rabbitmq/
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - desafio

  # redis:
  #   image: redis:6.2.14-alpine3.19
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
  #   volumes:
  #     - ./.redis_data:/data
  #   networks:
  #     - desafio

  localstack:
    image: localstack/localstack:3.1.0
    container_name: localstack
    labels:
      - group=main
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=0
      - AWS_DEFAULT_REGION=sa-east-1
    # volumes:
    #   - "./.localstack_data:/var/lib/localstack"
    networks:
      - desafio

  mongodb:
    image: mongo:6.0.13-jammy
    container_name: mongodb
    labels:
      - group=main
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    # volumes:
    #   - ./.mongo_data:/data/db
    networks:
      - desafio

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.18
    container_name: mongo-express
    labels:
      - group=main
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo_express
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - desafio
