version: "3.8"

services:
  develop:
    image: deirofelippe/develop-anotaai-challenge:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: develop
    ports:
      - 3030:3030
    volumes:
      - "./:/home/node/app"
