@url = http://localhost:3000

###
GET {{url}}/ HTTP/1.1

###
DELETE {{url}}/clear-db HTTP/1.1

###
GET {{url}}/v1/all HTTP/1.1

###
POST {{url}}/v1/categories HTTP/1.1
Content-Type: application/json

{
    "owner": "123",
    "title": "Computadores",
    "description": "Peças"
}

###
PATCH {{url}}/v1/categories HTTP/1.1
Content-Type: application/json

{
    "owner": "123",
    "category": "Computadores",
    "fields": {
        "title": "Computadores",
        "description": "Teste"
    }
}

###
POST {{url}}/v1/products HTTP/1.1
Content-Type: application/json

{
    "owner": "123",
    "category": "Computadores",
    "title": "RTX 3060",
    "description": "Peças",
    "price": 2000.00
}

###
PATCH {{url}}/v1/products HTTP/1.1
Content-Type: application/json

{
    "owner": "123",
    "category": "Computadores",
    "product": "RTX 3060 Atualizado",
    "fields": {
        "title": "RTX 3060 Atualizado",
        "description": "Peças Atualizado",
        "price": 1500
    }
}

###
GET {{url}}/v1/owners/1/categories HTTP/1.1